-- Put required config files here
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
-- require "user.statusline"
require "user.lualine"
require "user.transparent"
require "user.toggleterm"
-- require "user.project"
require "user.impatient"
-- require "user.indentline"
require "user.alpha"
require "user.whichkey"
-- require "user.quickscope"
require "user.hop"
require "user.matchup"
require "user.numb"
require "user.dial"
require "user.colorizer"
require "user.spectre"
-- require "user.todo-comments"
-- require "user.bookmark"
require "user.symbol-outline"
require "user.git-blame"
require "user.gist"
require "user.gitlinker"
require "user.surround"
require "user.notify"
require "user.ts-context"
require "user.telescope-file-browser"
require "user.sniprun"
require "user.functions"
require "user.copilot"
-- require "user.gps"
require "user.illuminate"
require "user.dap"
-- require "user.lir"
require "user.jabs"
require "user.cybu"
require "user.options"
require "user.nvim-webdev-icons"
require "user.orgmode"
require "user.neorg"
require "user.orgbullets"
require "user.iron"
